fix(deps): update dependencies
adfinis/ember-uikit pull request #1240
Opened 2024-06-11 14:30 UTC by anehx

2024-06-12 06:55 UTC, Yelinz requested changes
older ember versions are failing, maybe change the test version matrix?

2024-06-12 07:28 UTC, anehx commented
@Yelinz Fixed by adding `ember-resolver@11.0.1` to the dependencies of ember < 4.12 scenarios.

2024-06-12 07:29 UTC, Yelinz approved these changes

2024-06-12 07:29 UTC, merged

2024-07-05 07:46 UTC, anehx commented
:tada: This PR is included in version 9.1.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ember-uikit/v/9.1.2)
- [GitHub release](https://github.com/adfinis/ember-uikit/releases/tag/v9.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: